import type { TypeId } from "@/data/types"

export interface Description {
  base: string
  phase: string
}

export const DESCRIPTIONS: Record<TypeId, Description> = {
  travaillomane: {
    base:
      "Tu abordes le monde comme un ensemble de pièces à comprendre et à ordonner : avant de t'engager, tu veux saisir la logique, vérifier les faits et repérer la cohérence d'ensemble. Tu penses en catégories claires, tu classes l'information, tu démontes un problème pour en exposer la mécanique, et c'est cette rigueur qui te rend fiable quand les autres se perdent dans le flou. Ta tête travaille volontiers en arrière-plan, à reformuler, à trier l'essentiel de l'accessoire, jusqu'à ce qu'une structure nette se dessine. On peut compter sur ta parole précise, sur ta capacité à structurer une réflexion confuse et à transformer une intuition en plan applicable. La zone de vigilance se situe là où ta soif de précision peut te couper du ressenti : à trop vouloir tout maîtriser et tout justifier, tu risques de différer la décision, de surcharger les autres de détails ou d'oublier que toute donnée n'a pas besoin d'être parfaite pour être utile.",
    phase:
      "En ce moment, ce qui te porte, c'est de sentir que la qualité de ton travail est vue et reconnue à sa juste valeur, pas seulement le résultat brut mais le soin que tu y mets. Tu te sens vivant quand on prend le temps de constater ta compétence, quand un cadre temporel clair te dit où tu vas et combien de temps tu as devant toi. Les repères de planning, les échéances explicites et les attentes précises t'apaisent et libèrent ton énergie au lieu de la dévorer. À l'inverse, l'imprécision, les consignes mouvantes ou le sentiment que ton effort passe inaperçu te crispent et te poussent à en faire toujours plus pour exister. Reconnaître ce moteur, c'est t'autoriser à demander explicitement la reconnaissance et la clarté dont tu as besoin, plutôt que d'attendre qu'elles viennent d'elles-mêmes.",
  },
  perseverant: {
    base:
      "Tu regardes le monde à travers le prisme de tes valeurs et de tes convictions : face à une situation, ta première question intérieure est de savoir si c'est juste, fiable et digne qu'on s'y engage. Tu te forges des opinions solides, tu observes les gens et les projets à l'aune de ce en quoi ils croient, et tu accordes ta confiance à ce qui te semble cohérent dans la durée. Cette boussole intime fait de toi quelqu'un de loyal, capable de tenir un cap quand d'autres flanchent, et d'apporter du sens et de la profondeur là où il n'y aurait que de l'opportunisme. On vient chercher ton avis parce qu'il est réfléchi, assumé et fidèle à une ligne. La zone de vigilance apparaît quand ta fermeté se durcit : à force de filtrer le réel par tes convictions, tu peux entendre une simple information comme un jugement, t'arc-bouter sur un principe ou exiger des autres une rigueur morale qu'ils ne partagent pas forcément.",
    phase:
      "Ce qui t'anime en ce moment, c'est de sentir que tes convictions et ton engagement sont reconnus et respectés, que ce à quoi tu crois compte vraiment aux yeux de ceux qui t'entourent. Tu as besoin qu'on prenne au sérieux ton avis, qu'on reconnaisse la sincérité de ton implication et la cohérence de ta démarche. Quand on te consulte sur le fond, quand on te confie une cause ou une responsabilité qui a du sens, ton énergie se déploie pleinement. À l'inverse, te sentir ignoré, contredit sans égard ou traité comme interchangeable réveille une tension et te pousse à défendre ton territoire de valeurs avec plus de raideur. Mettre des mots sur ce besoin, c'est te donner la liberté de chercher des espaces où ton engagement est accueilli au lieu d'être perpétuellement à prouver.",
  },
  empathique: {
    base:
      "Tu perçois le monde d'abord par l'émotion et par le lien : en entrant dans une pièce, tu sens l'ambiance avant même qu'un mot soit dit, tu captes les non-dits, les tensions et les besoins de chacun. Ta sensibilité te rend attentif au confort des autres, tu sais accueillir, rassurer, créer ce climat de chaleur où les gens se sentent acceptés tels qu'ils sont. Cette finesse relationnelle est une vraie force : tu apaises les conflits, tu repères celui qui va mal, tu tisses des liens durables et sincères qui donnent à un groupe sa cohésion. Les gens se confient à toi parce que ta présence est douce et sans jugement. La zone de vigilance se loge dans ce don même : à force de t'ajuster aux autres et de craindre de déplaire, tu peux t'oublier, accepter ce qui ne te convient pas, et laisser tes propres besoins s'effacer jusqu'à l'épuisement.",
    phase:
      "Ce qui te nourrit en ce moment, c'est d'être reconnu non pas pour ce que tu fais mais pour qui tu es, en tant que personne, dans une relation chaleureuse et bienveillante. Tu as besoin de contacts attentionnés, d'un mot gentil, d'un signe qui te dit que ta présence compte et qu'on tient à toi. La proximité affective, l'attention sincère et les petites marques de tendresse rechargent ton énergie bien plus que n'importe quel résultat. À l'inverse, la froideur, l'indifférence ou un climat purement utilitaire te laissent un vide et peuvent réveiller le doute de n'être aimé que pour ton utilité. Reconnaître ce moteur, c'est t'autoriser à rechercher activement la chaleur dont tu as besoin et à l'accueillir sans culpabilité, comme un droit légitime et non comme une faiblesse.",
  },
  reveur: {
    base:
      "Tu perçois le monde par l'imaginaire et la réflexion intérieure : avant d'agir, tu observes, tu prends du recul et tu laisses les idées mûrir dans le calme de ton univers mental. Tu as une vie intérieure riche, peuplée d'images, de scénarios et de possibles, et tu sais voir une situation sous un angle que personne d'autre n'avait envisagé. Ce retrait te donne une vraie profondeur : tu réfléchis sans te précipiter, tu apportes des perspectives originales, et tu gardes ton calme là où d'autres s'agitent. Ta présence discrète est un point d'ancrage, et ta capacité à imaginer ouvre des portes inattendues. La zone de vigilance tient à ce même besoin de recul : à force de rester en observation, tu peux t'isoler plus que nécessaire, repousser le passage à l'action, ou attendre qu'on vienne te chercher au point de te rendre invisible et de te priver de ce que le contact aurait pu t'apporter.",
    phase:
      "Ce dont tu as besoin en ce moment, ce sont des espaces de solitude et de calme où ton imaginaire peut respirer sans être sollicité de toutes parts. Tu te ressources dans le retrait, dans un temps à toi, sans bruit ni demande pressante, où tu peux simplement laisser tes pensées vagabonder. On t'aide vraiment quand on te laisse l'espace de réfléchir à ton rythme et qu'on te dit clairement ce qu'on attend sans te submerger. À l'inverse, le trop-plein de stimulation, l'urgence permanente ou l'obligation d'être sans cesse en interaction t'épuisent et te font te replier davantage. Mettre des mots sur ce besoin, c'est t'autoriser à ménager ces bulles de tranquillité comme une nécessité vitale, et non comme une fuite ou un caprice.",
  },
  rebelle: {
    base:
      "Tu réagis au monde au quart de tour, en « j'aime / j'aime pas », avec une spontanéité qui ne triche pas : ton ressenti immédiat est ta boussole et tu n'as pas besoin de longs détours pour savoir ce qui t'amuse ou t'ennuie. Cette vitalité te rend créatif, joueur et vivant : tu détournes les codes, tu trouves l'angle drôle, tu mets de la couleur et de la légèreté là où l'ambiance se faisait pesante. Ton humour est contagieux, ton énergie débloque les situations figées, et ta créativité jaillit d'autant mieux que le cadre est ludique. Les gens aiment ta présence parce que tu rends le quotidien plus léger et plus vivant. La zone de vigilance se trouve dans cette même spontanéité : quand le plaisir manque ou que la contrainte pèse trop, tu peux te braquer, râler, faire de la résistance passive ou rejeter la faute au-dehors plutôt que de t'atteler à la part ingrate de la tâche.",
    phase:
      "En ce moment, ce qui te recharge, c'est le contact ludique, le jeu et la légèreté glissés dans ton quotidien : tu as besoin de rire, de t'amuser, de sentir que la vie n'est pas qu'une suite d'obligations sérieuses. Une touche d'humour, une activité divertissante, une ambiance détendue où l'on peut plaisanter ensemble suffisent à rallumer ton énergie. Tu donnes le meilleur de toi quand on partage avec toi ce ton complice et pétillant, quand on accueille ta fantaisie au lieu de la rabouer. À l'inverse, le sérieux permanent, la rigidité et l'absence totale de plaisir t'éteignent et réveillent ton envie de te rebiffer. Reconnaître ce moteur, c'est t'autoriser à réclamer ta dose de jeu et de fun, non comme une distraction futile mais comme un véritable carburant.",
  },
  promoteur: {
    base:
      "Tu lis le monde en actions et en opportunités : là où d'autres analysent, tu vois déjà le coup à jouer, l'occasion à saisir, le mouvement à enclencher. Direct, charmeur et débrouillard, tu vas droit au but, tu t'adaptes vite, tu n'as pas peur du risque et tu sais entraîner les autres dans ton élan. Cette audace fait de toi quelqu'un qui débloque, qui ose, qui transforme une situation immobile en terrain de jeu et obtient des résultats là où l'hésitation paralyserait. Tu as le sens du rapport de force et du timing, et ton aplomb rassure dans les moments où il faut trancher. La zone de vigilance se niche dans cette intensité : à foncer sans toujours mesurer les conséquences, tu peux brûler les étapes, bousculer les autres, privilégier le court terme et l'effet immédiat au détriment des liens, de la prudence ou de la profondeur durable.",
    phase:
      "Ce qui te fait vibrer en ce moment, c'est l'action, le défi et l'intensité vécue dans l'instant présent : tu as besoin que ça bouge, que ça pulse, qu'il y ait un enjeu réel à relever ici et maintenant. Le calme plat t'ennuie ; c'est l'adrénaline d'un objectif ambitieux, d'une compétition ou d'un pari un peu fou qui réveille toute ta puissance. On t'embarque vraiment quand on te lance un challenge à ta mesure et qu'on te laisse l'espace de foncer et de prouver ce dont tu es capable. À l'inverse, la routine, l'attentisme et l'absence d'enjeu te rendent fébrile et te poussent à provoquer l'événement pour ne pas t'éteindre. Mettre des mots sur ce besoin, c'est t'autoriser à chercher les terrains de jeu intenses qui te font exister, tout en veillant à ce qu'ils ne consument pas tout sur leur passage.",
  },
}
